AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Metadata:
  AWS::ServerlessRepo::Application:
    Name: NvaDataciteMds
    Description: Backend for communicating with the DataCite MDS API
    Author: Unit
    SemanticVersion: 1.0.0
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE

Globals:
  Function:
    Timeout: 20

Parameters:
  DataCiteMdsConfigs:
    Description: Institution configs for DataCite MDS API
    Default: '{{resolve:secretsmanager:dataCiteMdsConfigs:SecretString}}'
  EventBusName:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: nvaEventBusName
    Description: AWS EventBridge Event Bus Name.
  EventBusArn:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: nvaEventBusArn
  DlqArn:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: nvaDlqArn

Resources:
  FindableDoiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-draft-doi-handler
      Handler: no.unit.nva.datacite.handlers.FindableDoiEventHandler::handleRequest
      Runtime: java11
      MemorySize: 1408
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBusName
          AWC_ACCOUNT_ID: !Ref AWS::AccountId
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  type:
                    - doi.publication
                  item:
                    doiRequest:
                      status:
                        - APPROVED
                    doi:
                      - exists: true
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: SQS
            Destination: !Ref DlqArn
          OnFailure:
            Type: SQS
            Destination: !Ref DlqArn
