AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Metadata:
  AWS::ServerlessRepo::Application:
    Name: NvaDoiRegistrarClient
    Description: Client for communicating with DOI Registrars (DataCite)
    Author: Unit
    SemanticVersion: 1.0.0
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE

Globals:
  Function:
    Timeout: 20

Parameters:

  DataCiteMdsHost:
    Type: String
    Default: mds.test.datacite.org
  DataCiteRestHost:
    Type: String
    Default: api.test.datacite.org
  DataCitePort:
    Type: String
    Default: 443
  EventBusName:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: nvaEventBusName
  EventBusArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: nvaEventBusArn
  CustomerSecretsSecretName:
    Type: String
    Default: dataCiteCustomerSecrets
  CustomerSecretsSecretKey:
    Type: String
    Default: dataCiteCustomerSecrets

Resources:

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaDefaults
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - sts:AssumeRole
                  - sts:TagSession
                Resource: "*"
        - PolicyName: Events
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:*
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:*
                  - lambda:InvokeFunction
                Resource: "*"


  DataCiteDraftDoiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: datacite-draft-doi-handler
      Handler: no.unit.nva.datacite.handlers.DraftDoiHandler::handleRequest
      Runtime: java11
      MemorySize: 1408
      Environment:
        Variables:
          EVENT_BUS: !Ref EventBusName
          AWC_ACCOUNT_ID: !Ref AWS::AccountId
          CUSTOMER_SECRETS_SECRET_NAME: !Ref CustomerSecretsSecretName
          CUSTOMER_SECRETS_SECRET_KEY: !Ref CustomerSecretsSecretKey
          DATACITE_REST_HOST: !Ref DataCiteRestHost
          DATACITE_PORT: !Ref DataCitePort
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              detail-type: [ "Lambda Function Invocation Result - Success" ]
              detail:
                responsePayload:
                  type:
                    - doi.publication
                  item:
                    doiRequest:
                      status:
                        - APPROVED
                    doi:
                      - exists: false
                    sameModifiedDateForDoiRequest:
                      - true
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: SQS
            Destination: !GetAtt DataCiteDraftDoiHandlerDLQ.Arn
          OnFailure:
            Type: SQS
            Destination: !GetAtt DataCiteDraftDoiHandlerDLQ.Arn

  DataCiteDraftDoiHandlerDLQ:
    Type: "AWS::SQS::Queue"



