AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Metadata:
  AWS::ServerlessRepo::Application:
    Name: NvaDataciteMds
    Description: Backend for communicating with the DataCite MDS API
    Author: Unit
    SemanticVersion: 1.0.0
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE

Globals:
  Function:
    Timeout: 20

Parameters:
  DataCiteMdsConfigs:
    Description: Institution configs for DataCite MDS API
    Default: '{{resolve:secretsmanager:dataCiteMdsConfigs:SecretString}}'
